spring.application.name=Econexo
spring.profiles.active=dev

###SPRING DOC PROPERTIES (SWAGGER)###
springdoc.packages-to-scan=com.tfi.econexo.controller
springdoc.show-actuator=true
springdoc.swagger.ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/swagger-ui.html
