spring.application.name=Econexo
spring.profiles.active=dev

###SPRING DOC PROPERTIES (SWAGGER)###
springdoc.packages-to-scan=com.tfi.econexo.controller
springdoc.show-actuator=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/swagger-ui.html

###JWT PROPERTIES###
security.jwt.private.key=${PRIVATE_KEY}
security.jwt.user.generator=${USER_GENERATOR}
security.jwt.expiration.minutes =${JWT_EXPIRATION_MINUTES:30}

###JACKSON PROPERTIES###
spring.jackson.property-naming-strategy=SNAKE_CASE
